<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ClickOpportunities</name>
   <tag></tag>
   <elementGuidId>04ffd9d4-25b1-42e9-a00c-2bd33548cc78</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@class='rlql-relatedListQuickLink']//div[@class='slds-grid']//a//span[contains(text(),'Opportunities')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
