<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PAOppPageVerify</name>
   <tag></tag>
   <elementGuidId>0867c095-831c-40a4-90d8-9fb8a4113b4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h1//slot[@name='primaryField']//lightning-formatted-text[contains(text(),'${value}')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
