<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ParentShadowRootElement</name>
   <tag></tag>
   <elementGuidId>61abba86-8e4f-4f31-8bee-432a7b902457</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>//sb-page-container[@id='sbPageContainer']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
