<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SaveButton</name>
   <tag></tag>
   <elementGuidId>8aee1356-826b-4b38-8034-c6ab7233fab0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//sb-custom-action[@name='Save']//paper-button[@id='mainButton']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
