<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SelectProduct-SelectionPage</name>
   <tag></tag>
   <elementGuidId>51cacb7c-ab8b-4d57-a4ac-c2f287ab6a95</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//sb-i18n[text()='Select']//parent::paper-button</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
