<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PartnerContractValue</name>
   <tag></tag>
   <elementGuidId>de57fe17-4f10-44b2-82cc-15e90bfbcafb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@data-target-selection-name=&quot;sfdc:RecordField.SBQQ__Quote__c.PartnerContract__c&quot;]//a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
