<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>QckAction_Setup</name>
   <tag></tag>
   <elementGuidId>1fcff293-9508-47c6-bdc0-a8df6fc3543e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div//lightning-icon[@icon-name='utility:setup']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
