<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BillingCountryGreenland</name>
   <tag></tag>
   <elementGuidId>e2cbe866-bd10-42f3-9401-893f943eb8a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class=&quot;select-options&quot;]//ul[@class=&quot;scrollable&quot;]//li//a[@title='Greenland']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
