<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SalesTerritoryValue</name>
   <tag></tag>
   <elementGuidId>983f24ef-dbf3-4838-844d-0ed9f3cb0310</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class=&quot;select-options&quot;]//ul[@class=&quot;scrollable&quot;]//li//a[@title='${value}']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
