<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>StatusFieldValue</name>
   <tag></tag>
   <elementGuidId>813ee2b2-6445-4454-8502-1dace8dd91f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//flexipage-record-home-with-subheader-template-desktop2//span[text()='Status']//..//..//lightning-formatted-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
