<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Phone</name>
   <tag></tag>
   <elementGuidId>a1ea9b17-706e-4cfb-8123-a4f04d685880</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*//label[contains(text(),&quot;Phone&quot;)]//..//div//*[@name='Phone']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
