<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SalutationNone</name>
   <tag></tag>
   <elementGuidId>7df73d49-853d-4d9b-ba69-a5b98f2b134c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*//label[contains(text(),&quot;Salutation&quot;)]//..//div//button//span[text()='--None--']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
