<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SalutationMs</name>
   <tag></tag>
   <elementGuidId>d1fe7649-7f60-449a-98c5-93be80a5c06f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*//label[contains(text(),&quot;Salutation&quot;)]//..//div//*[@data-value='Ms.']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
