<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SetUp</name>
   <tag></tag>
   <elementGuidId>a452d43c-b137-40ef-a91e-02808c6a7477</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div//lightning-icon[@icon-name='utility:setup']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
