<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SelectUserfromPeople</name>
   <tag></tag>
   <elementGuidId>e1754983-5922-4660-9897-15adf5c62794</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//th//a[@data-refid='recordId']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
