<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>GetStageValue</name>
   <tag></tag>
   <elementGuidId>bdc89135-2226-4392-9c66-503f43c78143</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//flexipage-field[@data-field-id='RecordStageNameField']//lightning-formatted-text[@slot='output']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
