<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Stage</name>
   <tag></tag>
   <elementGuidId>4a143146-7cd9-43f3-9182-c585b60360de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//flexipage-field[@data-field-id=&quot;RecordStageNameField&quot;]//span[text()='Stage']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
